jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: kse
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
      working-directory: kse
    - continue-on-error: true
      if: always()
      name: Publish Test Report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: kse/build/reports/tests/test/*
    - continue-on-error: true
      if: always()
      name: Publish Build
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: 'build/libs/kse.jar

          kse/build/distributions/kse-*.zip

          '
name: Build KSE and run tests
on:
  repository_dispatch:
    types: trigger-ga___build_test.yml
